language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn build
  - yarn test
deploy:
  - provider: pages # https://docs.travis-ci.com/user/deployment/pages/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: build
    on:
      branch: master
